### ISSUE TITLE
docker: Error response from daemon

### ISSUE THREAD

**Issue by liuquartz** [nsidc/NSIDC-Data-Access-Notebook#2]
once i quit the jupyter notebook i started in terminal with docker running, how could i start it again? i tried to follow the guidance again but i got an error like this:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint recursing_lovelace (283e0e1985b83cffb5615d65818f66c8f780f03c3fba00227e0c43a9bc5be5db): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.`

**Comment by betolink** [comment]
Are you running Docker on Windows? if so maybe this may work:

Stop all the running containers using PowerShell ```docker stop $(docker ps -a -q)``` 
then stop Docker on your machine & restart it.
