### ISSUE TITLE
capability url returns invalid request

### ISSUE THREAD

**Issue by fliphilipp** [nsidc/NSIDC-Data-Access-Notebook#5]
I have a workflow to request subsetted ICESat-2 data based on this data access notebook. It worked until yesterday, but now the capability url returns an invalid request. The same thing happens when running this notebook in Binder, for all the data product short names that I have tried. 
```
capability_url: https://n5eil02u.ecs.nsidc.org/egi/capabilities/ATL03.005.xml
response: <Response [400]> b'{"error":"invalid_request"}'
```

This triggers an error in the next line: 
```
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_168/938956396.py", line 13, in <module>
    root = ET.fromstring(response.content)

  File "/srv/conda/envs/notebook/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 1, column 0
```

Any idea what the issue could be here? 

Thanks, 
Philipp

**Comment by ccalvocm** [comment]
Greetings, I have a similar problem.

[image: image.png]
Carlos Calvo Cortés-Monroy, M.Sc.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
24/08/22,
18:40:35

**Comment by nsidc-bookerl** [comment]
Hello Carlos and Philipp -

I apologize for the errors. Our data archive is down for maintenance until 2pm US Mountain Time on Friday. If you attended our demonstration today, Leslie noted the banner message on our data set landing page that noted the maintenance. We apologize for failing to include a reminder during the notebook demonstration. Please try again after 2pm on Friday. 

Cheers,
NSIDC User Services

**Comment by fliphilipp** [comment]
Oh crap, I guess I can't read good! 😆 

Thanks for responding so quickly, I'll close the issue.
